# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "python"
      - "security"
    assignees:
      - "project-maintainer"
    reviewers:
      - "project-maintainer"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    versioning-strategy: "auto"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Monitor Prometheus configuration
  - package-ecosystem: "docker"
    directory: "/prometheus"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "monitoring"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Monitor Grafana configuration
  - package-ecosystem: "docker"
    directory: "/grafana"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "monitoring"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
