repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: detect-private-key
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=88]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile=black, --line-length=88]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-docstrings
        -   flake8-bugbear
        -   flake8-comprehensions
        -   flake8-simplify
        -   flake8-eradicate
        args: [--max-line-length=88, --extend-ignore=E203]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies:
        -   types-setuptools
        -   types-redis
        -   types-aiofiles
        -   types-python-dateutil
        -   types-requests
        -   types-urllib3
        args: [--strict, --ignore-missing-imports]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: [--configfile, pyproject.toml]

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
    -   id: python-safety-dependencies-check
        files: requirements*.txt

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/PyCQA/pylint
    rev: v2.17.5
    hooks:
    -   id: pylint
        args:
        -   --rcfile=pyproject.toml
        additional_dependencies:
        -   pylint-pytest

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [tests/]

    -   id: check-coverage
        name: check-coverage
        entry: coverage run -m pytest
        language: system
        pass_filenames: false
        always_run: true

default_language_version:
    python: python3.8

ci:
    autofix_commit_msg: 'style: auto fixes from pre-commit hooks'
    autoupdate_commit_msg: 'ci: update pre-commit hooks'
    skip: [pytest-check, check-coverage]
