discord:
  token: ${DISCORD_TOKEN}
  prefix: "!"
  status: "!help for commands"
  activity_type: "playing"

database:
  url: "sqlite:///data/bot.db"
  pool_size: 20

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/discord.log"

features:
  plex:
    enabled: true
    timeout: 30
    max_search_results: 5
    
  activities:
    enabled: true
    invite_duration: 3600  # 1 hour

  voice:
    enabled: true
    default_volume: 100
    timeout: 300  # 5 minutes of inactivity before disconnect

plex:
  url: ${PLEX_URL}
  token: ${PLEX_TOKEN} 