[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

[tool.flake8]
max-line-length = 120
exclude = ['.venv', '.git', '__pycache__', 'docs', 'build', 'dist']
extend-ignore = ["E203", "W503"] # Corrected line 21

[tool.coverage.run]
branch = true
source = ["src"]

[tool.pytest.ini_options]
addopts = "-ra -q --cov=src --cov-report term-missing"
python_files = "test_*.py"
testpaths = ["tests"]
asyncio_mode = "auto"
