apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-backup-config
  labels:
    app: redis-backup
data:
  REDIS_HOST: redis-master.default.svc.cluster.local
  REDIS_PORT: '6379'
  BACKUP_DIR: /backup
  BACKUP_RETENTION_DAYS: '7'
  REDIS_CONFIG: |
    # Performance tuning
    maxmemory 8gb
    maxmemory-policy volatile-lru
    maxmemory-samples 20

    # I/O optimization
    io-threads 12
    io-threads-do-reads yes
    dynamic-hz yes

    # Enhanced persistence
    aof-use-rdb-preamble yes
    rdb-save-incremental-fsync yes

    # Memory optimization
    active-defrag-ignore-bytes 200mb
    active-defrag-cycle-min 25
    jemalloc-bg-thread yes

    # Connection optimization
    tcp-keepalive 30
    tcp-backlog 4096
    maxclients 20000
