version: '3.9'
services:
  bot:
    build: .
    container_name: media_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - VOICE_CHANNEL_ID=${VOICE_CHANNEL_ID}
      - REDIS_URL=redis://redis:6379
    ports:
      - '8080:8080'
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    logging:
      driver: 'json-file'
      options:
        max-size: '200m'
        max-file: '10'

  redis:
    image: redis:7
    container_name: media_redis
    command: ['redis-server', '--save', '', '--appendonly', 'no']
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    driver_opts:
      com.docker.network.bridge.name: app_net
      com.docker.network.driver.mtu: 1500
