api_keys:
  openai: YOUR_OPENAI_API_KEY_HERE
  weather: YOUR_WEATHER_API_KEY_HERE
discord:
  client_id: YOUR_CLIENT_ID_HERE
  client_secret: YOUR_CLIENT_SECRET_HERE
  token: YOUR_DISCORD_TOKEN_HERE
plex:
  token: YOUR_PLEX_TOKEN_HERE
  url: YOUR_PLEX_URL_HERE
