discord:
  token: YOUR_DISCORD_TOKEN_HERE
  client_id: YOUR_DISCORD_CLIENT_ID_HERE
  client_secret: YOUR_DISCORD_CLIENT_SECRET_HERE
plex:
  server_url: YOUR_PLEX_URL_HERE # Changed from server_url to url to match PlexConfig
  token: YOUR_PLEX_TOKEN_HERE
api_keys:
  openai: YOUR_OPENAI_API_KEY_HERE
  weather: YOUR_WEATHER_API_KEY_HERE
